### ISSUE TITLE
Double license under MPL 2 and LGPL 3

### ISSUE THREAD

**Issue by garro95** [garro95/priority-queue#23]
Dear contributors,
Because of how Cargo works, it is currently easier to statically link external crates.

The GNU LGPL license, however, impose to link dynamically.

I am opening this issue to get your consent about double licensing this crate under both the LGPL and the MPL.

The Mozilla Public License is still a weak copyleft license, similar to the LGPL, but allowing static linking to software with a different license.

@lnicola @tsionyx @BourgondAries @ocecaco @petr-tik

**Comment by lnicola** [comment]
Apache-2/MIT is more popular in the Rust ecosystem, but it's fine if you prefer MPL.

---

I hereby consent to relicense my contribution to this repository under LGPL 3 and MPL 2.0.

**Comment by ocecaco** [comment]
Sure, I consent to licensing under LGPL 3 and MPL 2.0 as well.

**Comment by petr-tik** [comment]
Makes sense. 

I hereby consent to the relicensing of my contribution to this repository under LGPL 3 and MPL 2.0.

**Comment by tsionyx** [comment]
I am agreed with relicensing of my contribution too.

**Comment by BourgondAries** [comment]
I consent to licensing under LGPL 3 and MPL 2.0 as well.

**Comment by garro95** [comment]
This crate is now licensed under both the LGPL 3 and the MPL 2.0, at user's opinion

**Comment by DK26** [comment]
I may be wrong because I relied on ChatGPT to check this out for me (let me know if you know better), but it seems that both LGPL 3 and MPL 2.0, requires that we allow the user to modify and replace the library as they see fit. This is of course a little more problematic to comply with when using a single executable. This may require hacks to turns the library into a dynamically linked one or provide the full source code to the user in order for them to compile the project themselves. 

This basically means that if you try to use this library in a closed-source project in Rust, you must hack into a dynamically link solution (such as `.dll` file) or else you are violating the license. Should be considered as this is very limiting the use case to only be use in an open-source project. Unless this is what the project intended to begin with

**Comment by lnicola** [comment]
That's true for LGPL, but not for MPL. From https://www.mozilla.org/en-US/MPL/2.0/FAQ/:

> This allows, for example, programs using MPL-licensed code to be statically linked to and distributed as part of a larger proprietary piece of software, which would not generally be possible under the terms of stronger copyleft licenses.

From what I've seen, ChatGPT often gives wrong, but confident-sounding answers, so you should be a little discerning when applying its advice.

**Comment by DK26** [comment]
> That's true for LGPL, but not for MPL. From https://www.mozilla.org/en-US/MPL/2.0/FAQ/:
> 
> > This allows, for example, programs using MPL-licensed code to be statically linked to and distributed as part of a larger proprietary piece of software, which would not generally be possible under the terms of stronger copyleft licenses.
> 
> From what I've seen, ChatGPT often gives wrong, but confident-sounding answers, so one should be a little discerning when applying its advice.
> 
> You can work see in the issue description at the top that the motivation for relicensing to MPL 2.0 was allowing static linking in the way you describe.

Yeah, I figured this might be a mistake. Thanks for the quick answer. I had to make sure that ChatGPT was the one that is wrong and not the OP because of the OP intend and for me to consider the crate.
